# Generated by Django 3.0.6 on 2020-05-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sell', '0004_auto_20200509_0318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='contact',
            field=models.TextField(blank=True),
        ),
    ]
