# Generated by Django 3.0.6 on 2020-05-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sell', '0005_auto_20200509_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
