# Generated by Django 3.0.6 on 2020-05-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sell', '0006_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, default='3.png', upload_to=''),
        ),
    ]
