# Generated by Django 3.0.6 on 2020-05-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sell', '0010_auto_20200509_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, default='c.jpg', upload_to=''),
        ),
    ]
