# Generated by Django 3.0.3 on 2020-02-12 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20200213_0316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, upload_to='allbooks'),
        ),
        migrations.AlterIndexTogether(
            name='book',
            index_together={('id', 'slug')},
        ),
    ]
